### PR TITLE
Layout proposal

### PR DESCRIPTION
**Pull request by peterbraden**
This is a naming scheme for a center column that we've been using.

Also, include the sensible grid by default.

### CODE REVIEW

**Comment by meodai** [comment]
Not sure if I like the therm content, since everything is content. Feels a little like a variable called data. But as it is the main content it could be called main or copy. But is this ment as a boilerplate, or just for the readme? In the second case I'm fine with it,

**Comment by peterbraden** [comment]
I should give a little more information. 

Basically, on a lot of pages / webapps, all 'content' is centered in a center 'column' when the viewport gets bigger than a certain width. Sometimes things like images or background colors will stretch the full window width, but almost always, you want a max-width on the centered 'content' so that it doesn't look bad on ridiculously huge screens.

I'd like to settle on a common terminology to refer to these 'containers'. 

I'm not in love with 'content', but I also don't have a better suggestion - I've used these conventions in the past, but happy to change, as long as we can all adopt something. #naming-is-hard.

I tried to demo what I meant with the readme, but it's such a small page it's hard to understand I guess.

Re 'main' or 'copy' - the thing is meant to contain all 'content' so 'copy' doesn't really encompass it - it would also be used in navs, footers, carousels etc.

The same problem exists with 'main' - it makes me think of the <main /> element, which specifically should not include navs, and footers.

It is an ambiguous wrappers, so it will _have_ to have a fairly ambiguous name, but I'm happy to consider other options. Or even just name the thing Fred. It's mainly so we can talk in the group clearly about what this thing is.

**Comment by meodai** [comment]
what about `.main` or `.copy` well I tend to call this `.l-site-width` / `.l-design-width`

**Comment by lucalanca** [comment]
@meodai @peterbraden what about container?

**Comment by peterbraden** [comment]
I'm alright with container, but it's a widely used name, and I'd prefer to come up with something specific to this scenario. 

That being said, bootstrap use .container, so perhaps this is the right term.

**Pull request closed without merging**
