### PR TITLE
Optimise JS assets for production

### PR DESCRIPTION
**Pull request by lucalanca**
This PR adds generates optimised javascript assets for production.

### Development Build
Each javascript file is downloaded individually so it's easier to debug. This also means that the bower_components files are included.

screen shot 2015-05-07 at 14 42 34

Javascript files are in:
- ```components/*/*.js``` (components scripts)
- ```js/**/*.js``` (global scripts)
- ```bower_components/**/*.js``` (external dependencies)

All pages load the ```main.js``` file so you need to require the scripts you need:

```js
/*jslint browser: true */
/*global require: true, requirejs: true, $: true */

(function(){
    'use strict';

    /*
      This is how you should require a component:
      make sure `mycomponent` in the require-config situated in layout/layout.jade
     */
    /*
      require(['mycomponent'], function () {
          console.log('mycomponent is loaded');
      });
    */
   require([
      'globals',
      'button'
    ]);

})();
```
screen shot 2015-05-07 at 14 42 20

### Production Build
All files are bundled into a single one, which is also minimised. Thus, we only have 2 javascript files:
- require.js
- main.js (all the files such as bower dependencies, module scripts and global scripts) are bundled into this file.

screen shot 2015-05-07 at 14 45 48
screen shot 2015-05-07 at 14 45 36

## Grunt Tasks
I've renamed some tasks we had so their names are more consistent with the standard grunt-based generators:
- serve: starts server with non-optimised assets.
- serve-build: starts server with optimised assets
- build: generates the optimised build artefacts under /dist folder.

### Future Improvements
Right now we have to maintain all our require.js files in two locations:
- layout.jade (for the dev environment we need to reference javascript files with the relativePath as each file is individually downloaded asynchronously for each page.)
- config-require.js (This file is used to generate the build javascript bundle Note: we don't need to use relativePath here).

This is sub-optimal but I currently have no idea how to just have one file.

### CODE REVIEW

**Comment by lejoe** [comment]
Ok, I think there is some more improvements we could do but this is already better.
So I would say :+1: for merging.

@meodai ?

**Comment by meodai** [comment]
I can't give my :+1: since I:

1) I understand the problem but this solution does still makes no reasonable sense to me, maybe you need to explain it to me like im 5.
2) The solution looks much more complicated that it should be, and would totally scare me away as a potential new skeleton user

So of course you can mere it, since I will probably never like this solution for the second reason.

**Comment by lejoe** [comment]
@meodai  can you point me to the things that this PR makes worse than the current solution?

**Comment by meodai** [comment]
@lejoe of course: 

https://github.com/ginetta/Skeleton/blob/master/app/layout/layout.jade#L20
vs 
https://github.com/ginetta/Skeleton/commit/5c42977911c7d9fbc2bdb0ac03c93753b72c1ca8

looks pretty overwhelming to me.

**Comment by meodai** [comment]
But please feel free to merge it il branch my way out of this :D

**Comment by lejoe** [comment]
Hope you're only talking about the extra if/else. I which case I'd agree but that's the part that was not working yet in skeleton. Please help us if you know another way.

For the rest I believe you also see the value added to help requirejs noobs overcome it's complexity with those comments/guiding.

**Comment by meodai** [comment]
@lejoe of course I will, as soon as I have the opportunity to work with it...

**Comment by lucalanca** [comment]
@meodai this is much better now on https://github.com/ginetta/Skeleton/pull/52

**Pull request merged**
