### PR TITLE
Switching to grunt-jit (from load-grunt-tasks) & libsass (from compass)

### PR DESCRIPTION
**Pull request by idflood**
Started to switch to libsass. But we should wait untill I try this branch on a more complete project.

### CODE REVIEW

**Comment by idflood** [comment]
I made some test with the current Basler project. jit-grunt + libsass definitely make things much faster, here are some number taken from the watch task:

### Jade:
#### before

    loading tasks       2.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 54%
    pagesAssembler:dev  2.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 46%
    Total 5s

#### after

    loading tasks       443ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 15%
    pagesAssembler:dev   2.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 85%
    Total 2.9s


### Sass:
#### before

    loading tasks      2.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 61%
    sass:dev           1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%
    autoprefixer:all  147ms  ▇▇▇▇ 3%
    Total 4.4s

#### after

    loading tasks               444ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 55%
    loading grunt-sass           14ms  ▇▇ 2%
    sass:dev                     74ms  ▇▇▇▇▇▇▇▇▇▇ 9%
    loading grunt-autoprefixer  135ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%
    autoprefixer:all            137ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%
    Total 805ms

**Comment by idflood** [comment]
When switching existing project you may have to:

- run `npm install`
- delete the `node_modules/grunt-contrib-sass` folder since it will be loaded by default, even if `grunt-sass` is present.

**Comment by lejoe** [comment]
Nice job @idflood !
Looks great

**Comment by lucalanca** [comment]
Excelent :+1: 

Just as a note, this PR also includes grunt-jit, not only switching from ruby-sass to libsass.

**Comment by lejoe** [comment]
Merged directly to master as the styleguide branch is now there

**Pull request closed without merging**
