### PR TITLE
Ignores phpstorm project files

### PR DESCRIPTION
**Pull request by lejoe**

### CODE REVIEW

**Comment by meodai** [comment]
I think you should have things that are specific to your setup in your global gitignore. Otherwise we will bloat the gitignore of each project with whatever files whatever editor produces: https://help.github.com/articles/ignoring-files/

**Comment by peterbraden** [comment]
I agree with @meodai and would suggest that we don't need any of the current lines either, as they should all be in your global file: 

```
.DS_Store
  *.orig
  .tmp
 +.idea/*
```

**Comment by peterbraden** [comment]
Things that are appropriate are things like `node_modules` or `build` which are specific to the current project.

**Comment by meodai** [comment]
@peterbraden yes!

**Comment by meodai** [comment]
There is a good default one: https://gist.github.com/octocat/9257657 (I added some NPM stuff)

**Comment by peterbraden** [comment]
Added to my dotfiles repo :) 

https://github.com/peterbraden/dotfiles/commit/35a7dcfac1afc3d96903409ee3263b435940065f

**Comment by peterbraden** [comment]
If we have consensus, can we close this?

**Comment by meodai** [comment]
for me we can close it and make a new one where we remove the specific stuff and add a line to the readme?

**Comment by meodai** [comment]
Did a proposal here: https://github.com/ginetta/skeleton/pull/113

**Comment by lejoe** [comment]
Oh wow, that escalated quickly. Did not expect that much reaction as there usually isn't on PRs :)

All that to say I agree with you all. We did this PR with @haluvibe partly to test if we can push branches from projects to the skeleton directly. Sorry for the noise.

**Pull request closed without merging**
