### PR TITLE
V2/fix gulp task

### PR DESCRIPTION
**Pull request by corinneroelli**
This fixes the gulp task error: 
screen shot 2015-09-08 at 17 09 01

### CODE REVIEW

**Comment by lejoe** [comment]
@corinneroelli please do a pull request from your branch to v2/master not /master

**Comment by corinneroelli** [comment]
@lejoe Ok. I think you already did a new pr to v2/master. right?

On Tue, Sep 8, 2015 at 5:33 PM, lejoe <notifications@github.com> wrote:

> @corinneroelli <https://github.com/corinneroelli> please do a pull
> request from your branch to v2/master not /master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ginetta/skeleton/pull/66#issuecomment-138601882>.
>



-- 

GINETTA WEB/MOBILE

Lutherstrasse 32, CH-8004 Zürich, www.ginetta.net

Corinne Roelli, Frontend Developer

corinne@ginetta.net, +41 (0)79 103 38 81

**Comment by lejoe** [comment]
@corinneroelli nope did not do it yet

**Comment by corinneroelli** [comment]
I wanted to create a new pr but then I saw this:
https://github.com/ginetta/skeleton/pull/67
This is a new pr to v2/master. I didn't get it why it's already there.

On Tue, Sep 15, 2015 at 1:34 PM, lejoe <notifications@github.com> wrote:

> @corinneroelli <https://github.com/corinneroelli> nope did not do it yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ginetta/skeleton/pull/66#issuecomment-140359795>.
>



-- 

GINETTA WEB/MOBILE

Lutherstrasse 32, CH-8004 Zürich, www.ginetta.net

Corinne Roelli, Frontend Developer

corinne@ginetta.net, +41 (0)79 103 38 81

**Comment by lejoe** [comment]
hum, right. weird. perhaps I did after all because I needed it

**Pull request closed without merging**
