### PR TITLE
Gulp4 migration

### PR DESCRIPTION
**Pull request by lejoe**

### CODE REVIEW

**Comment by peterbraden** [comment]
Is there any way we can avoid calling t.getTask everywhere? Can we, ie do:
```
var task = function(name, subtask etc...){
return gulp.task(name, t.getTask(subtask))
}

task('foo', ['bar'])
```

**Comment by lejoe** [comment]
There's probably a way but would prefer to handle this in #86 and keep this about moving to gulp4.
Will come back to it there, I promise.

**Comment by peterbraden** [comment]
<3

**Comment by lejoe** [comment]
@meodai @lucalanca @peterbraden any other feedback on the move to gulp4 ?
Or can we merge it?

There's one thing that I'm not happy yet. Running gulp --tasks lists the tasks. It's the new standard on how to document tasks. But it's not as great as what we had before with the grunt-help:
image

**Comment by lucalanca** [comment]
@lejoe the code LGTM. Besides the new simplified API, does it provide any performance improvement (which the series/parallel execution for instance)?

**Comment by lejoe** [comment]
That's what they claim yes but with some few exaples in this project It's
hard to see

On Thu, Nov 12, 2015 at 4:13 PM, João Figueiredo <notifications@github.com>
wrote:

> @lejoe <https://github.com/lejoe> the code LGTM. Besides the new
> simplified API, does it provide any performance improvement (which the
> series/parallel execution for instance)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ginetta/skeleton/pull/99#issuecomment-156134139>.
>



-- 
GINETTA WEB/MOBILE Lutherstrasse 32, CH-8004 Zürich, www.ginetta.net Joel
Bez, Tech Lead joel@ginetta.net, +41 (079) 234-0513

**Comment by lejoe** [comment]
Also, the new watch now fixes it's bugs with new files

**Comment by lejoe** [comment]
Ok this is ready for a final review.
To review, please go to the [website](https://github.com/ginetta/website) project, create a new branch. pull from this branch and test it out.

I want someone else than me to do it to make sure it works with your environment.

**Pull request merged**
